### PR TITLE
Sbhuller/app confgen remake

### LINKED ISSUE #62: Update integration test documentation
Update integration test documentation to better align with dunedaq-v3.1.0 as well as how daq_application tests should now be run.
Coupled to issue https://github.com/DUNE-DAQ/flxlibs/issues/61.

### PR DESCRIPTION
**Pull request by ShyamB97**
Remake App confgen to create configs to run in nanorc.
Closes Issues https://github.com/DUNE-DAQ/flxlibs/issues/61 and https://github.com/DUNE-DAQ/flxlibs/issues/62

### CODE REVIEW

**Comment by ShyamB97** [comment]
Need to run integration tests and update documentation before merging

**Comment by ShyamB97** [comment]
@jimbrooke Integration tests passed with new configurations, the documentation has been updated accordingly.

**Review by jimbrooke — COMMENTED** [review]
Hey @ShyamB97 this looks good to me.  But should it make use of https://github.com/DUNE-DAQ/flxlibs/blob/develop/python/flxlibs/cardcontrollerapp/cardcontrollerapp_gen.py ?

**Comment by ShyamB97** [comment]
@jimbrooke I think we can make use of cardcontrollerapp_gen.py, but we would need to make the number of links and logical units configurable. So we would need to open another PR and make those changes in https://github.com/DUNE-DAQ/flxlibs/blob/develop/python/flxlibs/cardcontrollerapp/cardcontrollerapp_gen.py.

**Review by jimbrooke — COMMENTED** [review]
LGTM

**Pull request merged**
